package com.example.musicplayer.Music_Stuff

class Constants {
    companion object {
        const val APP_INFO = "Developed By Zahra Amirinezhad \n\n" +
                "My Contacts : \n" +
                "https://www.linkedin.com/in/zahra-amirinezhad-896240231/ \n\n" +
                "Some of My Projects : \n" +
                "https://github.com/zahraamirinezhad/"
        const val INDEX = "index"
        const val CLASS = "class"
        const val FAVOURITES_SHUFFLE = "FavouritesShuffle"
        val GMAIL = "zahraamiri1381216@gmail.com"
        val GMAIL_PASSWORD = "kagurasougo"
        val STH_WENT_WRONG = "Something Went Wrong :("
        val WANNA_GO = "Do You Want to Close the App ?"
        val YES = "YES"
        val NO = "NO"
        val MAIN_ACTIVITY = "MainActivity"
        val ARTIST = "ARTIST"
        val ALBUM = "ALBUM"
        val MUSIC = "MUSIC"
        val SHOW_BY = "ShowBy"
        val SHOW_BY_PASSWORD = "SHOW BY"
        val CONTENT = "content"
        val SONG_IMAGE = "SONG IMAGE"
        val STOP_TIMER = "STOP TIMER"
        val WANNA_STOP_TIMER = "Do You Want to Stop the Timer ?"
        val TYPE_FOR_SHARE = "audio/*"
        val SHARE = "Share Music File !!"
        val PLAYER_MENU = "PLAYER MENU"
        val SONG_LYRICS = "SONG LYRICS"
        val REC_MU_IS_PLAYING = "RecentMusicIsPlaying"
        val PLAYLIST_DETAILS_SHUFFLE = "PlaylistDetailsShuffle"
        val ALBUM_DETAILS_SHUFFLE = "AlbumDetailsShuffle"
        val PLAYLIST_DETAILS_ADAPTER = "PlaylistDetailsAdapter"
        val ALBUM_DETAILS_ADAPTER = "AlbumDetailsAdapter"
        val RECENT_MUSIC = "RecentMusic"
        val MUSIC_ADAPTER = "MusicAdapter"
        val MUSIC_ADAPTER_SEARCH = "MusicAdapterSearch"
        val NOW_PLAYING = "NowPlaying"
        val FAVOURITE_ADAPTER = "FavoriteAdapter"
        val ARTIST_DETAILS_ADAPTER = "ArtistDetailsAdapter"
        val ALBUM_VIEW_PLAY = "AlbumViewPlay"
        val ROTATION = "rotation"
        val UNKNOWN = "Unknown"
        val ALARM_SUCCESSFULLY = "Set as Alarm Ringtone Successfully "
        val ALARM_UN_SUCCESSFULLY = "Unable to Set as Alarm Ringtone "
        val ALLOW_MODIFY_SYSTEM_SETTINGS_NO = "Allow Modify System Settings ==> ON "
        val RINGTONE_SUCCESSFULLY = "Set as Ringtone Successfully "
        val RINGTONE_UN_SUCCESSFULLY = "Unable to Set as Ringtone "
        val PACKAGE = "package:"
        val PLAYLIST_NAME = "PLAYLIST NAME"
        val ADD = "ADD"
        val PLAYLIST_EXIST = "Playlist Exist !!"
        val DAY_FORMATTER = "yyyy.MM.dd"
        val REMOVE_ALL_MUSICS = "Remove All The Musics"
        val WANNA_REMOVE_ALL_MUSICS = "Do You Want to Remove All the Musics in this Playlist ?"
        val SETTINGS = "SETTINGS"
        val APP_VERSION = "1.0.0"
        val ALBUM_NAME = "Album Name"
        val SONG_AMOUNT = "Song Amount"
        val SORT_ORDER = "SORT ORDER"
        val SORTING_ALBUM = "SORTING_ALBUM"
        val SORT_ORDER_FOR_ALBUM = "SORT ORDER FOR ALBUM"
        val ARTIST_NAME = "Artist Name"
        val SORTING_ARTIST = "SORTING_ARTIST"
        val SORT_ORDER_FOR_ARTIST = "SORT ORDER FOR ARTIST"
        val RECEANTLY_ADDED = "Recently Added"
        val SONG_TITLE = "Song Title"
        val FILE_SIZE = "File Size"
        val SORTING = "SORTING"
        val ITS_FROM_PLAY_BTN = "ItsFromPlayBTN"
        val PLAY_SONG_FIRST = "Play A Song First!!"
        val SELECT_PALY_LIST = "SELECT PLAYLIST"
        val MUSICS_ADDED_SUCCESSFULLY = "Musics Added Successfully"
        val SELLECT_PLAYLIST = "SELECT PLAYLIST"
        val REMOVE = "Remove"
        val WANNA_DELETE_PLAYLIST = "Do you want to delete this playlist ?"
        val CANT_REMOVE_CURRENT_PLAYING = "Can't Remove Currently Playing Song."
        val LYRICS_ADDED_SUCCESSFULLY = "Lyrics Saved Successfully :)"
        val NO_LYRICS = "There is No Lyrics to Save :("
        val NOW_PLAYING_SONG = "Now Playing Song"
        val IMPORTANT_CHANNEL = "This is a important channel for showing songs !!"
        val OK = "OK"
        val SAVED_INFO = "savedInfo"
        val FAVOURITE_SONGS = "FavouriteSongs"
        val PLAYLISTS = "Playlists"
        val RECENT_MUSIC_CURRENT_POSITION = "RecentMusicCurrentPosition"
        val RECENT_MUSIC_CURRENT_POSITION_IN_SEEKBAR = "RecentMusicCurrentPositionInSeekBar"
        val RECENT_MUSIC_IS_PLAYING = "RecentMusicIsPlaying"
        val ALL_LYRICS = "AllMusicsLyrics"
        val MUSIC_ADDRESS = "content://media/external/audio/albumart"
        val FALSE = "false"
        val MY_MUSIC = "My Music"
        val EXIT = "Exit"
        val PLAY = "Play"
        val REPEAT = "Repeat"
        val PREVIOUS = "Previous"
        val NEXT = "Next"
    }
}